# Generated by Django 5.1 on 2024-09-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_profile_bio'),
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description')),
                ('is_negotiable', models.BooleanField(default=False)),
                ('expected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_harvest_date', models.DateTimeField(blank=True, null=True)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.produce')),
            ],
        ),
    ]
