# Generated by Django 5.1 on 2024-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expected_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quantity',
        ),
        migrations.AddField(
            model_name='post',
            name='price_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GHC', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expected_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Tons', null=True),
        ),
    ]
