# Generated by Django 5.1 on 2024-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
