# Generated by Django 5.1 on 2024-09-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_verified_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
