# Generated by Django 5.1 on 2024-09-06 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='farmer_response',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PurchaseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_responses', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_request.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='farmers_responded',
            field=models.ManyToManyField(related_name='responses', through='purchase_request.PurchaseResponse', to=settings.AUTH_USER_MODEL),
        ),
    ]
