# Generated by Django 5.1 on 2024-09-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bio'),
        ('purchase_request', '0002_remove_purchaserequest_farmer_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='factory',
        ),
        migrations.AddField(
            model_name='purchaseresponse',
            name='price_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per ton', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='farmers_responded',
            field=models.ManyToManyField(related_name='responses', through='purchase_request.PurchaseResponse', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per ton', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseresponse',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_responses', to='accounts.profile'),
        ),
    ]
