# Generated by Django 5.1 on 2024-09-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0003_remove_purchaserequest_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(help_text='Quantity in tons'),
        ),
    ]
