# Generated by Django 5.1 on 2024-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0004_alter_purchaserequest_quantity_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseresponse',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
