# Generated by Django 5.1 on 2024-09-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_quantity'),
        ('produce', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post',
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='produce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produce.produce'),
        ),
    ]
